### 1 Write a function to compute 5/0 and use try/except to catch the exceptions.¶


In [3]:
def abc(x,y):
    try:
        a=x//y
        print("yeah I got answer",a)
    except ZeroDivisionError:
        print("sorry you are diving by 0")

In [4]:

abc(5,0)

sorry you are diving by 0


In [5]:
abc(5,2)

yeah I got answer 2


### Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].¶


In [7]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [8]:
for i in subjects :
    for j in verbs:
        for k in objects:
            print( i + " " + j + " " + k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### 1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [3]:
def matix(list_element,nthpower):
    X = []
    for num in list_element:
        for i in range(1,nthpower+1):
            X.append(num ** i)
    return np.array(X).reshape(len(list_element),n)

In [4]:
import numpy as np
n=4
list_element = [1,2,3,4,5]
elements = len(list_element)
result = np.array(matix(list_element,n))
print(result)

[[  1   1   1   1]
 [  2   4   8  16]
 [  3   9  27  81]
 [  4  16  64 256]
 [  5  25 125 625]]
